### ISSUE TITLE
This is problematic.

### ISSUE THREAD

**Issue by n0psled** [PeterAaser/semproj#1]
Hello, just spotted a couple of problems, and they are _not_ OK. 

Firstly, you have spelt project as "prosjekt". The main issue is the alarming lack of strong women, or _any_ women for that matter in your bibliography. Please update this as soon as possible.

Thanks.

**Comment by PeterAaser** [comment]
fixed in commit 79eda9711a35b6d5e23e39fd16bc996719306f3c
